/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Opportunity Hub API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export interface SuccessResponse {
  message: string;
}

export interface RegisterRequest {
  email: string;
  /** @minLength 6 */
  password: string;
  name: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface FreelancerProfile {
  id: number;
  email: string;
  name: string;
  subscription_status: string;
  created_at: string;
}

export interface AuthResponse {
  user: FreelancerProfile;
  token: string;
}

export type LeadLeadQuality =
  (typeof LeadLeadQuality)[keyof typeof LeadLeadQuality];

export const LeadLeadQuality = {
  HOT: "HOT",
  GOOD: "GOOD",
  MEDIUM: "MEDIUM",
} as const;

export interface Lead {
  id: number;
  client_name: string;
  service_needed: string;
  lead_quality: LeadLeadQuality;
  description?: string | null;
  budget?: string | null;
  created_at: string;
}

export interface Skill {
  id: number;
  freelancer_id: number;
  skill_name: string;
  created_at: string;
}

export interface AddSkillRequest {
  skill_name: string;
}
